server:
  port: 8090

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/person
    username: thomas
    password: thomas

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb+srv://thomascaycedo19:fcy-pxt6kbr2wfv4ECJ@clusterimage.49efi7t.mongodb.net/?retryWrites=true&w=majority
      database: photo

appDescription: "Person API"
appVersion: "1.0.0"